# Python to Linux Web App on Azure
trigger:
- master

variables:
  azureServiceConnectionId: 'ac9fac07-bd8f-4649-acd8-1aa7087bd04f'
  webAppName: 'django-fruits-app-project'
  vmImageName: 'ubuntu-latest'
  environmentName: 'django-fruits-app-project'
  projectRoot: $(System.DefaultWorkingDirectory)/sports_shop_proj  # Updated to point to Django root
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        
        # Install dependencies
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn  # Required for production deployment
        
        # Collect static files (ensure STATIC_ROOT is set in settings.py)
        python manage.py collectstatic --noinput
      workingDirectory: $(projectRoot)  # Now points directly to Django project
      displayName: "Install requirements and prepare Django"

    - script: |
        source antenv/bin/activate
        python manage.py check --deploy
        python manage.py migrate --noinput
      workingDirectory: $(projectRoot)
      displayName: "Verify and run migrations"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              runtimeStack: 'PYTHON|3.11'
              startupCommand: 'gunicorn --bind 0.0.0.0:8000 sports_shop_proj.wsgi'
              appSettings: |
                [
                  {
                    "name": "DJANGO_SETTINGS_MODULE",
                    "value": "sports_shop_proj.settings"
                  },
                  {
                    "name": "WEBSITE_PORT",
                    "value": "8000"
                  }
                ]